### ISSUE TITLE
Potential Bug with Genetic Algorithm Function

### ISSUE THREAD

**Issue by nlachapelle** [gkhayes/mlrose#33]
While using the genetic algorithm function for a class project, I was getting poorer performance than expected, and after looking into the code to gain some insight I think I have found an issue. When the algorithm gets into the while (attempts < max_attempts) loop, the new population is bred from the original, and then the fitness of the new population is tested, which makes perfect sense. However, in order to test the fitness, the original population gets overridden, and even when the new fitness is worse than the original the population is never reverted back and the next attempt is based off of the population that performed worse. 

Here is the code (algorithms.py, inside genetic_alg function):

        next_gen = np.array(next_gen)
        **problem.set_population(next_gen)                        <---- Population gets changed**

        next_state = problem.best_child()
        next_fitness = problem.eval_fitness(next_state) 

        # If best child is an improvement,
        # move to that state and reset attempts counter
        if next_fitness > problem.get_fitness():
            problem.set_state(next_state)
            attempts = 0

        **else:                       <---- If fitness is worse, there is no revert back to original population**
            attempts += 1

Maybe this implementation was intentional, but this doesn't seem like ideal functionality. If this was in fact done intentionally, and someone knows the reasoning, please let me know. It's got me curious

**Comment by gkhayes** [comment]
Hi @nlachapelle ,

I had a look through the section of code that you pointed out, and I don't think there is a bug there. Here are the reasons why:
- What we want to do is to optimize the fitness function and return the state that results in the optimal fitness value and the fitness value of that state (i.e. best_state and best_fitness in the code). We are not interested in finding the population that gave rise to that state.
- When we create the new population, although we change the population at the line you pointed out, we don't change the fitness and state values of the problem. 
- The fitness and state values are only updated if we find that the best child of the new population results in a better state (this is done at this section of the code):
```
if next_fitness > problem.get_fitness():
     problem.set_state(next_state)
```
- The fact that the population is overridden at each attempt to find a better state doesn't matter, since the population is just a means to an ends.

I hope that makes sense. If not, please feel free to ask questions and I'll do my best to answer them.

Genevieve.
