### ISSUE TITLE
Question on inital states for GA and MIMIC

### ISSUE THREAD

**Issue by YMa508** [gkhayes/mlrose#48]
Got a question. Why initial state is not a parameter for GA and MIMIC (unlike RHC and SA) while it is always reset ?

**Comment by walintonc** [comment]
@YMa508 - The algorithms are essentially different. In GA for example, what you have is an initial population that per definition [1] is selected at random and the "state" is basically the "most fit" element from the population. The population keeps "evolving" until some state is found that meets some fitness threshold. Specifically to answer your question, the GA algorithm does not have such thing as an "initial state" in Rusell's definition. One could argue that the initial population, instead of being selected at random, could be provided to the algorithm and that would be your initial state, but that's outside the discussion at least for this particular implementation. MIMIC probably follows similar reasoning.

[1] Russell, S. and P. Norvig (2010). *Artificial Intelligence: A Modern Approach*, 3rd edition.
